package my.fatura;
import javax.swing.SpinnerListModel;
/**
 * @author mumta
 */
public class FaturaForm extends javax.swing.JFrame {
    
    public String getFaturaTuru() {
        return jSpinner1.getValue().toString();
    }

    public String getAboneAdi() {
        return jTextField1.getText();
    }

    public String getAboneTipi() {
        if (jRadioButton1.isSelected()) {
            return "isyeri";
        } else if (jRadioButton2.isSelected()) {
            return "ev";
        } else {
            return "";
        }
    }
    
    public int getSonEndex() {
        try {
            return Integer.parseInt(jTextField3.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    public int getIlkEndex() {
        try {
            return Integer.parseInt(jTextField4.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    public int getTuketimTutari() {
        try {
            return Integer.parseInt(jTextField2.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    /**
     * Creates new form FaturaForm
     */
    public FaturaForm() {
        initComponents();
        SpinnerListModel spinnerModel = new SpinnerListModel(new String[]{"su", "elektrik", "dogalgaz"});
        jSpinner1.setModel(spinnerModel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fType = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        aboneName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        aboneType = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        last = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        first = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        diff = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        para = new javax.swing.JLabel();
        kom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fType.setText("Fatura Türü:");

        aboneName.setText("Abone Adı:");

        aboneType.setText("Abone Tipi:");

        jRadioButton1.setText("İşyeri");

        jRadioButton2.setText("Ev");

        last.setText("Son Endex:");

        first.setText("İlk Endex:");

        diff.setText("Tüketim Tutarı:");

        jTextField2.setEditable(false);

        jButton1.setText("Hesapla...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aboneType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboneName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jSpinner1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(para, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fType, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jSpinner1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboneName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboneType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(para)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String faturaTuru = getFaturaTuru();
        String aboneAdi = getAboneAdi();
        String aboneTipi = getAboneTipi();
        int sonEndex = getSonEndex();
        int ilkEndex = getIlkEndex();
        int tuketimMiktari = sonEndex - ilkEndex;

        System.out.println("Fatura Turu: " + faturaTuru);
        System.out.println("Tuketim Tutari: " + tuketimMiktari);
        System.out.println("Abone Adi: " + aboneAdi);
        System.out.println("Abone Tipi: " + aboneTipi);
        System.out.println("Son Endex: " + sonEndex);
        System.out.println("Ilk Endex: " + ilkEndex);
        
        jTextField2.setText(Integer.toString(tuketimMiktari));
        
        int tutar=0;
        float komisyon=0;
        if(faturaTuru.equals("su")){
            System.out.println("debug");
            if(aboneTipi.equals("ev")){
                if(tuketimMiktari>20){
                    tutar=tuketimMiktari*3-20;
                }
                else{
                    tutar=tuketimMiktari*2;
                }
            }
            else if(aboneTipi.equals("isyeri")){
                if(tuketimMiktari>100){
                    tutar=tuketimMiktari*4-100;
                }
                else{
                    tutar=tuketimMiktari*3;
                }
            }
            komisyon=(float)tutar*5/1000;
        }
        else if(faturaTuru.equals("elektrik")){
            if(aboneTipi.equals("ev")){
                if(tuketimMiktari>150){
                    tutar=tuketimMiktari*2-150;
                }
                else{
                    tutar=tuketimMiktari;
                }
            }
            else if(aboneTipi.equals("isyeri")){
                if(tuketimMiktari>500){
                    tutar=tuketimMiktari*3-500;
                }
                else{
                    tutar=tuketimMiktari*2;
                }
            }
            komisyon=(float)tutar*3/1000;
        }
        else if(faturaTuru.equals("dogalgaz")){
            if(aboneTipi.equals("ev")){
                if(tuketimMiktari>100){
                    tutar=tuketimMiktari*4-100;
                }
                else{
                    tutar=tuketimMiktari*3;
                }
            }
            else if(aboneTipi.equals("isyeri")){
                if(tuketimMiktari>500){
                    tutar=tuketimMiktari*5-500;
                }
                else{
                    tutar=tuketimMiktari*4;
                }
            }
            komisyon=(float)tutar*2/1000;
        }
        
        System.out.println("Tutar:" + tutar + "TL");
        System.out.println("Komisyon: " + komisyon + "TL");
        
        para.setText("Fatura tutarınız:" + Integer.toString(tutar));
        kom.setText("Komisyon ücreti:" + Float.toString(komisyon));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboneName;
    private javax.swing.JLabel aboneType;
    private javax.swing.JLabel diff;
    private javax.swing.JLabel fType;
    private javax.swing.JLabel first;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel kom;
    private javax.swing.JLabel last;
    private javax.swing.JLabel para;
    // End of variables declaration//GEN-END:variables
}
